# src/pipeline.py

import logging
import pandas as pd
from datetime import date, timedelta

logger = logging.getLogger(__name__)

# =========================
# IMPORT SCHEDULERS
# =========================

from src.scheduler.kimsim import schedule_kimsim
from src.scheduler.teaching_tuesday import schedule_teaching_tuesday
from src.scheduler.imc_updates import schedule_imc_updates
from src.scheduler.trauma_schockraum import schedule_trauma
from src.scheduler.bedside import schedule_bedside
from src.scheduler.tte import schedule_tte
from src.scheduler.masterclass import schedule_masterclass
from src.scheduler.fpr import schedule_fpr
from src.scheduler.nds_fallbesprechung import schedule_nds
from src.scheduler.ofobi import schedule_ofobi
from src.scheduler.interprof_therapieplanung import schedule_therapy
# NEW
from src.scheduler.montagscurriculum import schedule_montagscurriculum
from src.scheduler.pflegeassistenten import schedule_pflegeassistenten
from src.scheduler.sitzungen import schedule_sitzungen
from src.scheduler.diverse import schedule_diverse
from src.scheduler.fokus_intensivpflege import schedule_fokus_intensivpflege  
from src.scheduler.epic_update import schedule_epic_update
from src.scheduler.fachentwicklung import schedule_fachentwicklung

from src.scheduler.tuesday import build_tuesday_schedule
from src.scheduler.wednesday import build_wednesday_schedule, build_topic_map
from src.scheduler.friday import build_friday_schedule

from src.selector import SmartFairSelector
from src.metadata import EVENT_METADATA
from src.feiertage import FEIERTAGE_DATES, get_feiertag_name

from src.utils_names import format_people
from src.data_loader import merge_overrides_into_history


# =========================
# MODULE-LEVEL CONSTANTS
# =========================

# Events generated by the algorithm (tuesday/wednesday/friday schedulers).
# Sheet-driven events are kept on Feiertage; these are removed.
# Single source of truth — previously redefined in 3 pipeline functions.
ALGORITHM_EVENTS: frozenset = frozenset({
    "COD_SENIOR",
    "COD_JUNIOR",
    "PEER",
    "PHYSIO",
    "Mittwoch_Curriculum",
    "Journal_Club",
    "Therapieplanung",   # fixed but auto-generated every Thursday
})


# =========================
# GLOBAL DATE PARSER
# =========================

def parse_date(x):
    return pd.to_datetime(x, errors="coerce", dayfirst=True).normalize()


# =========================
# SCHEMA FIXER
# =========================

def ensure_schema(df):

    required = ["date", "time", "event_type", "responsible", "topic", "room"]
    # Optional per-row columns that some schedulers attach (e.g. diverse.py
    # sets per-row Zielgruppe checkboxes). These must survive the schema fixer,
    # otherwise export_docx falls back to the all-audiences default and every
    # box gets checked. Preserved only when actually present on the frame.
    optional = ["zielgruppe", "zg_unknown"]

    if df is None or df.empty:
        return pd.DataFrame(columns=required)

    df = df.copy()

    for col in required:
        if col not in df.columns:
            df[col] = None

    df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.normalize()

    keep = required + [c for c in optional if c in df.columns]
    return df[keep]


# =========================
# SHEET EVENT BUILDER
# =========================

def _build_sheet_events(data: dict) -> list:
    """
    Build and schema-validate all sheet-driven event DataFrames.
    Returns a list ready for pd.concat — call this once per pipeline
    invocation instead of repeating 20 lines in every function.

    Algorithm events (tuesday/wednesday/friday) are NOT included here
    since they require a calendar and selector; callers append those.
    """
    def get(key):
        df = data.get(key)
        return df if df is not None else pd.DataFrame()

    return [
        ensure_schema(schedule_kimsim(get("sim"))),
        ensure_schema(schedule_teaching_tuesday(get("teaching"))),
        ensure_schema(schedule_imc_updates(get("imc"))),
        ensure_schema(schedule_trauma(get("trauma"))),
        ensure_schema(schedule_bedside(get("bedside"))),
        ensure_schema(schedule_tte(get("tte"))),
        ensure_schema(schedule_masterclass(get("masterclass"))),
        ensure_schema(schedule_nds(get("nds"))),
        ensure_schema(schedule_ofobi(get("ofobi"))),
        ensure_schema(schedule_montagscurriculum(get("montagscurriculum"))),
        ensure_schema(schedule_pflegeassistenten(get("pflegeassistenten"))),
        ensure_schema(schedule_sitzungen(get("sitzungen"))),
        ensure_schema(schedule_diverse(get("diverse"))),
        ensure_schema(schedule_fpr(get("fpr"))),
        ensure_schema(schedule_fokus_intensivpflege(get("fokus"))),
        ensure_schema(schedule_epic_update(get("epic"))),
        ensure_schema(schedule_fachentwicklung(get("fachentwicklung"))),
    ]


# =========================
# CALENDAR
# =========================

def generate_calendar(year, month):
    """
    Generate all weekdays in the given month, excluding public holidays
    (Feiertage Kanton Bern). Holidays are skipped so that Tuesday/Wednesday/
    Friday schedulers never produce algorithm-generated events on those days.
    Sheet-driven events are added separately and are unaffected.
    """
    start = date(year, month, 1)
    rows = []
    d = start

    while d.month == month:

        ts = pd.Timestamp(d)

        # skip weekends
        if d.weekday() <= 4:

            # skip public holidays — algorithm events won't be generated
            if ts.normalize() not in FEIERTAGE_DATES:
                rows.append({
                    "date": ts,
                    "weekday": d.strftime("%A"),
                    "weekday_num": d.weekday(),
                    "day": d.day,
                    "week": d.isocalendar()[1]
                })
            else:
                logger.info(
                    "[Feiertag] Skipped %s (%s) from calendar",
                    d.strftime('%A %d.%m.%Y'), get_feiertag_name(ts)
                )

        d += timedelta(days=1)

    return pd.DataFrame(rows).sort_values("date").reset_index(drop=True)


def add_weekday_position(calendar):

    calendar = calendar.sort_values("date")

    calendar["weekday_position"] = (
        calendar.groupby("weekday").cumcount() + 1
    )

    return calendar


# =========================
# PERSON STATS
# =========================

def build_person_stats(pep_df):

    if pep_df is None or pep_df.empty:
        return {"first_seen": {}}

    first_seen = (
        pep_df.groupby("name_clean")["date"]
        .min()
        .to_dict()
    )

    return {"first_seen": first_seen}


# =========================
# ENRICHMENT
# =========================

def enrich_schedule(df):

    df = df.copy()

    rooms = []
    topics = []

    for _, row in df.iterrows():

        meta = EVENT_METADATA.get(row["event_type"], {})

        room = row.get("room") or meta.get("room", "")
        prefix = meta.get("prefix", "")
        topic = str(row.get("topic", "") or "")

        if prefix:

            if "Case of the Day" in topic:
                topic = prefix

            elif prefix not in topic:
                topic = f"{prefix} {topic}".strip()

        rooms.append(room)
        topics.append(topic)

    df["room"] = rooms
    df["topic"] = topics

    return df


# =========================
# FRIDAY CONFLICT RESOLUTION
# =========================

def resolve_friday_conflicts(df):

    df = df.copy()

    df["weekday"] = df["date"].dt.day_name()

    cleaned = []

    for date, group in df.groupby("date"):

        if group["weekday"].iloc[0] != "Friday":
            cleaned.append(group)
            continue

        has_bedside = (group["event_type"] == "Bedside_Infektiologie").any()

        if has_bedside:
            group = group[group["event_type"] != "Journal_Club"]

        cleaned.append(group)

    return pd.concat(cleaned).drop(columns=["weekday"])


# =========================
# MAIN PIPELINE
# =========================

def generate_full_schedule(year, month, data):
    """
    Single-month baseline schedule. Creates a fresh selector scoped to this
    month only — no cross-month fairness memory.

    NOTE: In production, generate_full_schedule_aware supersedes this for
    all months with PEP data. Retained for testing and as a fallback when
    PEP is empty.
    """
    def get_df(key):
        df = data.get(key)
        return df if df is not None else pd.DataFrame()

    calendar = add_weekday_position(generate_calendar(year, month))

    pep_df = get_df("pep").copy()
    pep_df["date"]       = pd.to_datetime(pep_df["date"], errors="coerce").dt.normalize()
    pep_df["duty_code"]  = pd.to_numeric(pep_df["duty_code"], errors="coerce").fillna(-1).astype(int)
    pep_df["role_code"]  = pep_df["role_code"].astype(str).str.strip()
    pep_df["name_clean"] = pep_df["name_clean"].astype(str).str.strip().str.lower()

    selector = SmartFairSelector(
        person_stats=build_person_stats(pep_df),
        history_df=get_df("history"),
        aa_type_map=data.get("aa_registry") or {},
    )

    therapy   = ensure_schema(schedule_therapy(calendar))
    tuesday   = ensure_schema(build_tuesday_schedule(calendar, get_df("physio"), pep_df, selector, physio_topics_df=get_df("physio_topics"), already_picked_physio_nrs=set()))
    wednesday = ensure_schema(build_wednesday_schedule(calendar, pep_df, get_df("mittwoch_topics"), selector))
    friday    = ensure_schema(build_friday_schedule(calendar, pep_df, selector))

    full = pd.concat(
        _build_sheet_events(data) + [therapy, tuesday, wednesday, friday],
        ignore_index=True,
    )

    full["date"] = pd.to_datetime(full["date"], errors="coerce").dt.normalize()
    full = full[(full["date"].dt.year == year) & (full["date"].dt.month == month)]

    # Remove algorithm-generated events on Feiertage; log for transparency
    on_holiday     = full["date"].isin(FEIERTAGE_DATES)
    is_algorithmic = full["event_type"].isin(ALGORITHM_EVENTS)
    removed = full[on_holiday & is_algorithmic].copy()
    full    = full[~(on_holiday & is_algorithmic)].copy()

    for _, r in removed.iterrows():
        logger.info(
            "[Feiertag] Removed %s on %s (%s)",
            r['event_type'], r['date'].strftime('%d.%m.%Y'), get_feiertag_name(r['date'])
        )

    full = enrich_schedule(full)
    full = resolve_friday_conflicts(full)  # Bedside Infektiologie replaces Journal Club on shared Fridays
    full = full.sort_values(["date", "time"])
    full["responsible"] = full["responsible"].apply(format_people)

    return full.reset_index(drop=True)


# =========================
# MULTI-MONTH AWARE SCHEDULE
# =========================

# In-process cache for the warm multi-month pass. Keyed by a signature of the
# inputs so that looping over months (one generate_full_schedule_aware call per
# month) reuses a single shared-selector pass instead of rebuilding an empty
# selector every call. This is what gives real cross-month fairness memory.
_AWARE_CACHE: dict = {}


def _aware_signature(year, all_pep_months, data):
    """Build a lightweight signature of the inputs that affect assignment."""
    import hashlib
    pep = data.get("pep")
    hist = data.get("history")
    parts = [str(year), ",".join(map(str, all_pep_months))]
    for df in (pep, hist):
        if df is not None and hasattr(df, "shape"):
            parts.append(f"{df.shape}")
            try:
                # include a hash of the values so edits invalidate the cache
                parts.append(str(int(pd.util.hash_pandas_object(df, index=True).sum())))
            except Exception:
                parts.append(str(len(df)))
        else:
            parts.append("none")
    return hashlib.md5("|".join(parts).encode()).hexdigest()


def _get_aware_cache(year, all_pep_months, data, month):
    sig = _aware_signature(year, all_pep_months, data)
    entry = _AWARE_CACHE.get(sig)
    if entry is None:
        return None
    return entry.get(month)


def _store_aware_cache(year, all_pep_months, data, computed_months):
    sig = _aware_signature(year, all_pep_months, data)
    _AWARE_CACHE.clear()  # only keep the most recent input signature
    _AWARE_CACHE[sig] = computed_months


def clear_aware_cache():
    """Wipe the in-process warm-pass cache so the next schedule generation
    rebuilds from freshly loaded sheet data. Call this on every manual
    'Aktualisieren' / autoload, alongside st.cache_data.clear() and
    clear_alternatives_cache(). Without it, edits to any sheet other than
    PEP/History are masked until a full app restart, because the cache
    signature only hashes PEP and History."""
    _AWARE_CACHE.clear()


def generate_full_schedule_aware(year, month, data):
    """
    Generate the schedule for a single month using a shared selector that
    iterates all PEP months from the current month onward in chronological
    order, so assignment memory carries across months.

    Why start from the current month (not all PEP months):
      Past months are already finalised — re-running them would waste time
      and redundantly penalise people for assignments the history sheet
      already captures. The selector is pre-loaded with history on init,
      so past load is already factored into scoring.

    Falls back to generate_sheet_only_schedule if the requested month has
    no PEP data.

    Returns only the requested month's schedule.
    """
    import datetime

    def get_df(key):
        df = data.get(key)
        return df if df is not None else pd.DataFrame()

    pep_df_raw = get_df("pep").copy()

    if pep_df_raw.empty:
        return generate_sheet_only_schedule(year, month, data)

    pep_df_raw["date"]       = pd.to_datetime(pep_df_raw["date"], errors="coerce").dt.normalize()
    pep_df_raw["duty_code"]  = pd.to_numeric(pep_df_raw["duty_code"], errors="coerce").fillna(-1).astype(int)
    pep_df_raw["role_code"]  = pep_df_raw["role_code"].astype(str).str.strip()
    pep_df_raw["name_clean"] = pep_df_raw["name_clean"].astype(str).str.strip().str.lower()

    # Iterate only STRICTLY FUTURE months (relative to today). The current
    # month and all past months are excluded — past months are finalised and
    # already reflected in the history sheet that seeds the selector, and the
    # current month is treated as finalised too (per planning policy).
    #
    # "Future" is computed on the full (year, month) period, NOT the month
    # number alone, so a PEP plan that spans two calendar years (e.g. Dec 2026
    # + Jan 2027) is handled correctly and same-month-different-year never
    # collapses. We still iterate within THIS call's `year` scope, since the
    # caller passes one PLAN_YEAR per call and the calendar is built per-year.
    today = datetime.date.today()
    current_period = (today.year, today.month)

    # Distinct (year, month) periods present in the PEP data.
    pep_periods = sorted({
        (int(ts.year), int(ts.month))
        for ts in pep_df_raw["date"].dropna()
    })

    # Months belonging to THIS call's year that are strictly in the future.
    all_pep_months = sorted(
        m for (y, m) in pep_periods
        if y == year and (y, m) > current_period
    )

    if month not in all_pep_months:
        return generate_sheet_only_schedule(year, month, data)

    # If we already computed this exact warm pass (same year, same set of
    # months, same input data) on a previous per-month call, reuse it.
    cached = _get_aware_cache(year, all_pep_months, data, month)
    if cached is not None:
        return cached

    # ── Load overrides and merge into history BEFORE building the selector ──
    # Overrides represent slots the Planungsverantwortliche has already
    # manually assigned (e.g. by email). The selector must see these as
    # "already done" so it:
    #   (a) doesn't assign the same person again elsewhere (fairness)
    #   (b) doesn't count an overridden person as available for other slots
    # merge_overrides_into_history() appends override rows as synthetic
    # history entries, deduplicated against the real history by (date, event_type).
    _overrides_df = data.get("overrides_df")
    _history_with_overrides = merge_overrides_into_history(
        get_df("history"), _overrides_df
    )

    # Build a set of (date, event_type) pairs already covered by an override
    # so each per-month scheduler can skip those slots entirely instead of
    # generating a conflicting algorithmic assignment that apply_overrides()
    # would then have to patch over.
    #
    # _override_date_map: normalized_date -> event_type for Tuesday-type overrides.
    # Handles the case where the override specifies a type that differs from what
    # the algorithm computes for that date (e.g. PHYSIO on an odd-month Tuesday
    # that the algorithm generates as PEER). tuesday.py uses this to emit a
    # placeholder row with the override's type so apply_overrides() can match
    # it exactly by (date, event_type) and fill in the correct responsible person.
    _TUESDAY_TYPES = {"COD_SENIOR", "COD_JUNIOR", "PEER", "PHYSIO"}
    _override_slots: set = set()
    _override_date_map: dict = {}
    if _overrides_df is not None and not _overrides_df.empty:
        for _, _ov in _overrides_df.iterrows():
            _ov_date = pd.to_datetime(_ov.get("event_date"), errors="coerce")
            _ov_type = str(_ov.get("event_type", ""))
            if pd.notna(_ov_date) and _ov_type:
                _ov_norm = _ov_date.normalize()
                _override_slots.add((_ov_norm, _ov_type))
                if _ov_type in _TUESDAY_TYPES:
                    _override_date_map[_ov_norm] = _ov_type

    # One shared selector — history (+ overrides merged in) seeds past load;
    # selector accumulates current-year assignments month by month.
    selector = SmartFairSelector(
        person_stats=build_person_stats(pep_df_raw),
        history_df=_history_with_overrides,
        aa_type_map=data.get("aa_registry") or {},
    )

    # Sheet events are the same for every month iteration — build once.
    sheet_events = _build_sheet_events(data)

    target_schedule = None
    # Shared set — ensures each PHYSIO slot across months picks a different paper
    _physio_picked: set = set()
    # Shared topic map — same idea for Mittwochscurriculum. Built ONCE here so
    # the per-topic rotation survives the month loop below; rebuilding it per
    # month discarded the rotation and let the same person present the same
    # topic twice in one quarter. History seeds each topic's last_date so the
    # rotation also survives across runs, since the sheet column is never
    # written back.
    _mittwoch_topics = build_topic_map(get_df("mittwoch_topics"), _history_with_overrides)

    # Collect EVERY computed month, not just the target. The warm selector
    # pass already produces all of them; caching them means that when the
    # caller loops month-by-month (analyse.py, etc.) the cross-month
    # assignment memory is actually preserved instead of being thrown away
    # and recomputed from an empty selector on every call.
    computed_months: dict = {}

    for m in all_pep_months:

        calendar = add_weekday_position(generate_calendar(year, m))

        # therapy is calendar-dependent so it must be built per month
        therapy = ensure_schema(schedule_therapy(calendar))

        # Algorithm events — shared selector carries memory month-to-month
        tuesday   = ensure_schema(build_tuesday_schedule(calendar, get_df("physio"), pep_df_raw, selector, physio_topics_df=get_df("physio_topics"), already_picked_physio_nrs=_physio_picked, override_slots=_override_slots, override_date_map=_override_date_map))
        wednesday = ensure_schema(build_wednesday_schedule(calendar, pep_df_raw, get_df("mittwoch_topics"), selector, override_slots=_override_slots, topic_map=_mittwoch_topics))
        friday    = ensure_schema(build_friday_schedule(calendar, pep_df_raw, selector, override_slots=_override_slots))

        full = pd.concat(
            sheet_events + [therapy, tuesday, wednesday, friday],
            ignore_index=True,
        )

        full["date"] = pd.to_datetime(full["date"], errors="coerce").dt.normalize()
        full = full[(full["date"].dt.year == year) & (full["date"].dt.month == m)]

        # Remove algorithm-generated events on Feiertage (sheet events kept)
        full = full[
            ~(full["date"].isin(FEIERTAGE_DATES) & full["event_type"].isin(ALGORITHM_EVENTS))
        ].copy()

        full = enrich_schedule(full)
        full = resolve_friday_conflicts(full)  # Bedside Infektiologie replaces Journal Club on shared Fridays
        full = full.sort_values(["date", "time"])
        full["responsible"] = full["responsible"].apply(format_people)

        computed_months[m] = full.reset_index(drop=True)
        if m == month:
            target_schedule = computed_months[m]
            # Continue loop so selector stays warm for remaining months

    # Cache the whole warm pass so subsequent per-month calls with the same
    # inputs reuse it (preserving cross-month fairness memory).
    _store_aware_cache(year, all_pep_months, data, computed_months)

    return target_schedule if target_schedule is not None else pd.DataFrame()

def build_placeholder_schedule(calendar, physio_df):
    """
    Build algorithm-slot events with NO responsible person assigned.
    Used for months without PEP data — slots appear in the calendar so
    planners can see what needs to be filled, but responsible is blank.

    Mirrors the exact slot logic from tuesday.py, wednesday.py, friday.py:
      Tuesday:    COD_SENIOR (pos=1) / PHYSIO (even month pos=2) /
                  PEER / COD_JUNIOR (rotation)
      Wednesday:  Mittwoch_Curriculum (every Wednesday, topic from sheet)
      Friday:     Journal_Club (intermediate slot + AA slot shown as one row)
    """
    events = []

    # -------------------------
    # TUESDAY — same logic as tuesday.py, no assignment
    # -------------------------
    tuesdays = calendar[calendar["weekday"] == "Tuesday"]
    physio_index = 0

    for _, row in tuesdays.iterrows():
        d = row["date"]
        pos = row["weekday_position"]
        is_even_month = (d.month % 2 == 0)

        if pos == 1:
            subtype = "COD_SENIOR"
            topic   = "S - Case of the Day (COD)"

        elif is_even_month:
            if pos == 2:
                subtype = "PHYSIO"
                if physio_df is not None and not physio_df.empty:
                    topic = "Physio Teaching"  # article title used only in emails, not displayed
                else:
                    topic = "Physio Teaching"
                physio_index += 1
            elif pos % 2 == 1:
                subtype = "PEER"
                topic   = "Peer-Teaching Session"
            else:
                subtype = "COD_JUNIOR"
                topic   = "Case of the Day (COD)"

        else:
            if pos % 2 == 0:
                subtype = "PEER"
                topic   = "Peer-Teaching Session"
            else:
                subtype = "COD_JUNIOR"
                topic   = "Case of the Day (COD)"

        events.append({
            "date":       d,
            "time":       "11:30-11:45",
            "event_type": subtype,
            "responsible": None,   # placeholder — no PEP data
            "topic":      topic,
            "room":       "INO E218",
        })

    # -------------------------
    # WEDNESDAY — Mittwoch_Curriculum placeholder
    # -------------------------
    for _, row in calendar[calendar["weekday"] == "Wednesday"].iterrows():
        events.append({
            "date":       row["date"],
            "time":       "14:30-15:15",
            "event_type": "Mittwoch_Curriculum",
            "responsible": None,
            "topic":      "Mittwochscurriculum",
            "room":       "INO E218",
        })

    # -------------------------
    # FRIDAY — Journal Club placeholder (both slots shown as one row)
    # -------------------------
    for _, row in calendar[calendar["weekday"] == "Friday"].iterrows():
        events.append({
            "date":       row["date"],
            "time":       "14:30-15:15",
            "event_type": "Journal_Club",
            "responsible": None,
            "topic":      "Journal Club",
            "room":       "INO E218",
        })

    return pd.DataFrame(events) if events else pd.DataFrame()


# =========================
# SHEET-ONLY + PLACEHOLDER SCHEDULE
# =========================

def generate_sheet_only_schedule(year, month, data):
    """
    Generate a schedule for months without PEP roster data.

    - Sheet-driven events: fully populated (responsible, topic, room from sheet)
    - Algorithm slots (COD, PEER, PHYSIO, Mittwoch, Journal Club):
        appear as placeholders with responsible=None so planners can see
        which slots need to be filled manually.
    """
    def get_df(key):
        df = data.get(key)
        return df if df is not None else pd.DataFrame()

    calendar = add_weekday_position(generate_calendar(year, month))
    therapy  = ensure_schema(schedule_therapy(calendar))
    placeholders = ensure_schema(build_placeholder_schedule(calendar, get_df("physio")))

    full = pd.concat(
        _build_sheet_events(data) + [therapy, placeholders],
        ignore_index=True,
    )

    full["date"] = pd.to_datetime(full["date"], errors="coerce").dt.normalize()
    full = full[(full["date"].dt.year == year) & (full["date"].dt.month == month)]

    # Feiertage: sheet events kept, algorithm placeholders removed
    full = full[
        ~(full["date"].isin(FEIERTAGE_DATES) & full["event_type"].isin(ALGORITHM_EVENTS))
    ].copy()

    full = enrich_schedule(full)
    full = resolve_friday_conflicts(full)  # Bedside Infektiologie replaces Journal Club on shared Fridays
    full = full.sort_values(["date", "time"])
    full["responsible"] = full["responsible"].apply(format_people)
    full["month"] = month

    return full.reset_index(drop=True)
